name: Generate Contribution Animations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🐍 Gerar a Cobrinha (Snake)
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: letsmg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      # 👾 Gerar o Pacman (Versão Estável e sem bugs de XML)
      - name: Generate Pacman
        uses: m-radzikowski/pacman-contributions-action@v1.1.0
        with:
          github_user_name: letsmg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path: pacman-contribution-graph.svg
          # O tema dark combina com seu perfil
          theme: dark 

      # 💾 Commit e Push
      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add snake.svg snake-dark.svg pacman-contribution-graph.svg
          git commit -m "chore: update contribution animations [skip ci]" || echo "no changes"
          git push