name: Generate Contribution Animations

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: "0 */12 * * *" # Roda a cada 12 horas

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🐍 Gerar a Cobrinha (Snake)
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: letsmg
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark

      # 👾 Gerar o Pacman
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate pacman
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx pacman-contribution-graph \
          --username letsmg \
          --gameTheme github-dark \
          --output pacman-contribution-graph.svg

      # 💾 Commit e Push das imagens geradas
      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add snake.svg snake-dark.svg pacman-contribution-graph.svg
          git commit -m "chore: update contribution animations [skip ci]" || echo "no changes"
          git push